### ISSUE TITLE
Problem running Unipose

### ISSUE THREAD

**Issue by HardysJin** [mda84/High_Performance_Pose_Estimation#1]
Hi,

When I run
```
python run.py --input data/1.jpg
```
It gives me
```
Img to 2D Prediction: 1 / 1Traceback (most recent call last):
  File "run.py", line 121, in <module>
    run_uni_pose(args.model2D, args.input)
  File "run.py", line 85, in run_uni_pose
    canvas, joint_list = model_processor.predict(img_original, state, KF)
  File "/home/HwHiAiUser/git/High_Performance_Pose_Estimation/UniPose/processor_unipose.py", line 45, in predict
    kpts, im = self.post_process(result[0], input_var, img0)
  File "/home/HwHiAiUser/git/High_Performance_Pose_Estimation/UniPose/processor_unipose.py", line 87, in post_process
    kpts = get_kpts(heat, img_h=368.0, img_w=368.0)
NameError: name 'get_kpts' is not defined
```

`get_kpts` is not imported or defined in `processor_unipose.py` and I even searched `get_kpts` in entire project but failed to find the definition.

**Comment by mda84** [comment]
I had removed the function by mistake. I added it again.

**Comment by HardysJin** [comment]
Still having some problem even if i run it on your board (192.168.1.109); Since i didn't find this repo, only MHFormer but not runable, i cloned on `/home/HwHiAiUser/High_Performance_Pose_Estimation` but still not work.

**Comment by mda84** [comment]
On the same board, please go to this folder:
~/HIAI_PROJECTS/733_Project/High_Performance_Pose_Estimation/

For running the OpenPose, LighweightOpenPose and UniPose, run this command:
python run.py --input data/1.jpg

and for MHFormer, run this command:
python demo/vis.py --video 1.jpg

Right now I faced "Exception: acl.rt.set_device failed ret_int=507033", which seems to be a memory issue. I faced it sometimes before and then it resolved by itself!
