### ISSUE TITLE
Problem running MHFormer

### ISSUE THREAD

**Issue by HardysJin** [mda84/High_Performance_Pose_Estimation#2]
Hi,

The results in `demo/output` seem pretty good. But when I try:
```
python demo/vis.py --video 1.jpg
```
It gives me:
```
(1, 3, 416, 416)
(1, 416, 416, 3) uint8
**Current input data num 1 unequal to model input num 2**
Gen model input dataset failed
  0%|                                                                                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 304, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 96, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "/home/HwHiAiUser/git/High_Performance_Pose_Estimation/MHFormer/demo/lib/hrnet/gen_kpts.py", line 114, in gen_video_kpts
    bboxs, scores = model_processor_YOLO.predict(frame)
  File "/home/HwHiAiUser/git/High_Performance_Pose_Estimation/MHFormer/demo/processor_yolo.py", line 142, in predict
    print(output[0].shape)
TypeError: 'NoneType' object is not subscriptable
```
Seems it expects two inputs but only one given. I take a look the `om`, it requires two inputs with shapes `1,416,416,3` and `1,4`. According https://github.com/mda84/High_Performance_Pose_Estimation/blob/9c5a02fae428f681cbb55d0f49bcc2d64cabdd43/MHFormer/demo/processor_yolo.py#L141, only one input is given. I suspect the other input `1,4` is the input shape so I putted `np.array([1,416,416,3])` e.g.
```
output = self.model.execute([preprocessed_img, np.array([1, 416, 416, 3]).astype(np.uint8) ]) 
```
Output:
```
(1, 3, 416, 416)
(1, 416, 416, 3) uint8
[WARNING] Input[0] size: 519168 not equal om size: 259584, may cause inference result error, please check model input
[WARNING] Input[1] size: 4 not equal om size: 16, may cause inference result error, please check model input
```
The expected input size is `259584` but doesn't make sence to be consistant with `1, 416, 416, 3` because `1×416×416×3 = 519168` which is greater than `259584`. So each element is less than 1 bytes ? like `int4` ?

**Comment by mda84** [comment]
Would you please download yolov3_2.om from the same address and rename it to yolov3.om, and then replace the current file with it?
